'use strict';
const KEY='pdw27data', EVENT='PDW27', $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let people=[],station=localStorage.getItem('pdw27station')||'',active='home',selected=null,stream=null,frame=null;
function read(){const v=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(v))throw Error('Invalid saved data');return v}
try{people=read()}catch(e){alert('Saved attendee data could not be read. Please restore a backup. No data has been overwritten.');throw e}
function notice(s){$('notice').textContent=s;$('notice').hidden=false}
async function change(fn){const run=()=>{try{const next=read();fn(next);localStorage.setItem(KEY,JSON.stringify(next));people=next;stats();return true}catch(e){notice(e.message||'Could not save. Export a backup before continuing.');return false}};return navigator.locks? navigator.locks.request('pdw27-write',run):run()}
function stats(){for(const [id,key] of [['total',null],['reg','registration'],['snack','snack'],['lunch','lunch']])$(id).textContent=key?people.filter(p=>p[key]).length:people.length;$('stationLabel').textContent=station?({registration:'Registration & raffle',snack:'Snack station',lunch:'Lunch station'}[station]):'Choose station';}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;cancelAnimationFrame(frame)}
function home(){stopCamera();active='home';selected=null;$('content').hidden=true;$('orbitHome').hidden=false;stats()}
function mark(id){const seen=JSON.parse(localStorage.getItem('pdw27seen-v2')||'[]');if(!seen.includes(id)){seen.push(id);localStorage.setItem('pdw27seen-v2',JSON.stringify(seen))}document.querySelector(`[data-module="${id}"]`)?.classList.remove('new')}
function show(id){stopCamera();mark(id);active=id;selected=null;$('notice').hidden=true;$('orbitHome').hidden=true;$('content').hidden=false;const titles={registration:'Registration',walkin:'Walk-in registration',snack:'Snack claims',lunch:'Lunch claims',raffle:'Raffle',scan:'Scan QR pass',attendees:'Attendees & passes',report:'Reports & offline setup'};$('viewTitle').textContent=titles[id];const body=$('view');body.innerHTML='';if(['registration','snack','lunch','scan','attendees'].includes(id)){body.innerHTML=`${['snack','lunch'].includes(id)?`<p class="hint">Claims on this device: <strong>${esc(station)}</strong>. Use only one designated device per station.</p>`:''}<label for="query">Search name, attendee number, or scan QR</label><input id="query" placeholder="Name or PDW27 number" autocomplete="off"><div class="actions"><button id="camera">Scan with camera</button><label class="button secondary">Read QR screenshot<input type="file" id="qrImage" accept="image/*" hidden></label></div><video id="video" hidden playsinline muted></video><div id="scanStatus" role="status"></div><div id="results"></div><div id="detail"></div>`;$('query').oninput=renderSearch;$('camera').onclick=startCamera;$('qrImage').onchange=scanImage;renderSearch();}else if(id==='walkin'){body.innerHTML=station!=='registration'?'<p>Register walk-ins on the designated Registration & raffle device.</p>':`<form id="walkForm"><label for="wname">Full name</label><input id="wname" required maxlength="100" autocomplete="name"><label for="wmobile">Mobile (optional)</label><input id="wmobile" type="tel" maxlength="30"><button class="red">Register & create pass</button></form><div id="detail"></div>`;if($('walkForm'))$('walkForm').onsubmit=addWalkin;}else if(id==='raffle')renderRaffle();else renderReport();window.scrollTo(0,0)}
function renderSearch(){const query=$('query').value.trim().toLowerCase();$('results').innerHTML='';const matches=people.filter(p=>p.name.toLowerCase().includes(query)||p.id.toLowerCase().includes(query)).slice(0,50);if(!matches.length)$('results').innerHTML='<p>No participants found. Import your list in Reports or register a walk-in.</p>';for(const p of matches){const row=document.createElement('div');row.className='person';row.innerHTML=`<span><strong>${esc(p.name)}</strong><br><small>${esc(p.id)} · ${p.registration?'Checked in':'Not checked in'}</small></span>`;const b=document.createElement('button');b.textContent='Open';b.onclick=()=>openPerson(p.id);row.append(b);$('results').append(row)}}
function payload(p){return JSON.stringify({event:EVENT,id:p.id,name:p.name,walkin:!!p.walkin,checkedIn:!!p.registration})}
function qrCanvas(p,size=256){const qr=qrcode(0,'M');qr.addData(payload(p),'Byte');qr.make();const n=qr.getModuleCount(),cell=Math.max(3,Math.floor(size/(n+8))),c=document.createElement('canvas');c.width=c.height=(n+8)*cell;const cx=c.getContext('2d');cx.fillStyle='#fff';cx.fillRect(0,0,c.width,c.height);cx.fillStyle='#123f32';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(qr.isDark(y,x))cx.fillRect((x+4)*cell,(y+4)*cell,cell,cell);return c}
function pass(p){return `<div class="pass"><p class="eyebrow">PARKINSON’S DISEASE WARRIORS PHILIPPINES</p><h2><span class="redtext">GET TOGETHER</span> 2027</h2><h3>${esc(p.name)}</h3><strong>${esc(p.id)}</strong><div id="qr"></div><p class="rafflenumber">RAFFLE NO. ${esc(p.id.replace('PDW27-',''))}</p><div class="chips"><span class="chip">SNACK STUB</span><span class="chip">LUNCH STUB</span><span class="chip">RAFFLE STUB</span></div><p>Keep a screenshot. Present this QR at each station.</p><small>Staff records confirm claims and raffle entry.</small></div>`}
function openPerson(id){selected=id;const p=people.find(p=>p.id===id);if(!p)return;const d=$('detail');d.innerHTML=pass(p)+'<div class="actions" id="personActions"></div><div id="claimStatus" role="status"></div>';$('qr').append(qrCanvas(p));const add=(text,fn,disabled=false)=>{const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.onclick=fn;$('personActions').append(b)};add('Save pass image',()=>downloadPass(p));add(localStorage.getItem('pdw27-raffle-stub-seen')?'Save raffle stub':'NEW · Save raffle stub',()=>{downloadRaffleStub(p);localStorage.setItem('pdw27-raffle-stub-seen','1');openPerson(p.id)});if(station==='registration'){add(p.registration&&p.raffle?'Checked in · raffle entered':'Check in & enter raffle',()=>checkin(id),!!(p.registration&&p.raffle));}$('claimStatus').innerHTML=`<p>Snack: <strong>${p.snack?'Claimed '+esc(new Date(p.snack).toLocaleString()):'Available'}</strong><br>Lunch: <strong>${p.lunch?'Claimed '+esc(new Date(p.lunch).toLocaleString()):'Available'}</strong><br>Raffle: <strong>${p.raffle?'Entered':p.registration?'Checked in · entry pending':'Check in required'}</strong></p>`;if(['snack','lunch'].includes(station)&&[station,'scan'].includes(active))add(p[station]?'Already claimed':`Confirm ${station} claim`,()=>claim(id,station),!!p[station]);d.scrollIntoView({block:'start',behavior:'smooth'})}
async function checkin(id){if(station!=='registration')return notice('Use the registration device.');if(await change(list=>{const p=list.find(x=>x.id===id);if(!p)throw Error('Not found');const t=new Date().toISOString();p.registration=p.registration||t;p.raffle=p.raffle||t})){renderSearch();openPerson(id);notice('Checked in and entered in raffle.')}}
async function addWalkin(e){e.preventDefault();if(station!=='registration')return;const name=$('wname').value.trim(),mobile=$('wmobile').value.trim();if(!name)return;const norm=s=>s.toLowerCase().replace(/\s+/g,' ').trim();if(people.some(p=>norm(p.name)===norm(name))&&!confirm('This name is already listed. Is this a different participant?'))return;const id='PDW27-W'+crypto.randomUUID().slice(0,8).toUpperCase(),t=new Date().toISOString();if(await change(list=>list.push({id,name,mobile,walkin:true,registration:t,raffle:t,snack:null,lunch:null}))){$('walkForm').reset();openPerson(id);notice('Saved on this device. Participant can photograph the pass now.')}}
async function claim(id,k){if(station!==k)return notice('Use the assigned claim station.');if(await change(list=>{const p=list.find(x=>x.id===id);if(!p)throw Error('Participant not found');if(p[k])throw Error('Already claimed. A second claim was blocked.');p[k]=new Date().toISOString()})){openPerson(id);notice(`${k==='snack'?'Snack':'Lunch'} claim saved on this device.`)}}
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function downloadPass(p){const c=document.createElement('canvas');c.width=900;c.height=1190;const x=c.getContext('2d');x.fillStyle='#fffdf7';x.fillRect(0,0,900,1190);x.strokeStyle='#c9a45d';x.lineWidth=4;x.strokeRect(24,24,852,1142);x.fillStyle='#123f32';x.textAlign='center';x.font='bold 25px Arial';x.fillText('PARKINSON’S DISEASE WARRIORS PHILIPPINES',450,92);x.fillStyle='#b3202a';x.font='bold 55px Arial';x.fillText('GET TOGETHER 2027',450,180);x.fillStyle='#123f32';let font=42;do{x.font=`bold ${font--}px Arial`}while(x.measureText(p.name).width>810&&font>14);x.fillText(p.name,450,268);x.font='30px Arial';x.fillText(p.id,450,322);const qr=qrCanvas(p,480);x.imageSmoothingEnabled=false;x.drawImage(qr,(900-qr.width)/2,360);x.font='bold 30px Arial';x.fillText('RAFFLE NO. '+p.id.replace('PDW27-',''),450,930);x.font='bold 27px Arial';x.fillText('SNACK  •  LUNCH  •  RAFFLE',450,995);x.font='24px Arial';x.fillText('Present this saved pass at each station.',450,1060);x.font='20px Arial';x.fillText('Staff records confirm claims and raffle entry.',450,1110);c.toBlob(b=>{if(b)download(b,p.id+'-pass.png','image/png')})}
async function acceptCode(value){stopCamera();$('video').hidden=true;let data;try{data=JSON.parse(value)}catch{data={id:value.trim()}}if(data.event&&data.event!==EVENT)return notice('This QR belongs to another event.');if(typeof data.id!=='string'||!/^PDW27-[A-Za-z0-9-]{1,50}$/.test(data.id))return notice('Not a valid event pass.');let p=people.find(p=>p.id===data.id);if(!p){if(!data.walkin||typeof data.name!=='string'||data.name.length>100||!data.name.trim())return notice('Not on this device. Import the latest attendee list from Registration.');if(!confirm(`Walk-in: ${data.name}\n${data.id}\nThis pass is not in this device’s list. Verify it with registration staff before adding. Add it?`))return;if(!await change(list=>{if(!list.some(x=>x.id===data.id))list.push({id:data.id,name:data.name,walkin:true,registration:null,raffle:null,snack:null,lunch:null})}))return;}openPerson(data.id);notice('Pass found. Review participant before confirming a claim.')}
async function startCamera(){try{stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=$('video');v.srcObject=stream;v.hidden=false;await v.play();$('scanStatus').textContent='Point the camera at the saved QR. Tap Back to stop.';const c=document.createElement('canvas'),cx=c.getContext('2d',{willReadFrequently:true});const tick=()=>{if(!stream)return;if(v.readyState>=2){c.width=640;c.height=Math.round(640*v.videoHeight/v.videoWidth);cx.drawImage(v,0,0,c.width,c.height);const img=cx.getImageData(0,0,c.width,c.height),code=jsQR(img.data,img.width,img.height);if(code){acceptCode(code.data);return}}frame=requestAnimationFrame(tick)};tick()}catch(e){stopCamera();notice('Camera unavailable. Allow camera access, upload a QR screenshot, or search by name.')}}
async function scanImage(e){const file=e.target.files[0];if(!file)return;try{const bitmap=await createImageBitmap(file),c=document.createElement('canvas'),scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));c.width=bitmap.width*scale;c.height=bitmap.height*scale;const x=c.getContext('2d');x.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const img=x.getImageData(0,0,c.width,c.height),code=jsQR(img.data,img.width,img.height);if(code)await acceptCode(code.data);else notice('QR not found. Use a clear, uncropped image or search the name.')}catch{notice('Could not read this image. Try a JPG or PNG.')}}
function renderRaffle(){const entered=people.filter(p=>p.registration&&p.raffle),winners=entered.filter(p=>p.won);$('view').innerHTML=`<div class="bigCount">${entered.length}</div><p>Checked-in raffle entries on this device</p><p>Use the designated Registration & raffle device for the official draw.</p><button id="findStub" class="secondary">Find participant & save raffle stub</button><p></p><button id="draw" ${station!=='registration'?'disabled':''}>Draw one winner</button><div id="winner" aria-live="polite"></div><h3>Winners</h3><div id="winners">${winners.map(p=>`<p><strong>${esc(p.name)}</strong> · ${esc(p.id)}<br><small>${esc(new Date(p.won).toLocaleString())}</small></p>`).join('')||'<p>No winners drawn yet.</p>'}</div>`;$('findStub').onclick=()=>show('attendees');$('draw').onclick=async()=>{if(station!=='registration')return;let winner;const ok=await change(list=>{const pool=list.filter(p=>p.registration&&p.raffle&&!p.won);if(!pool.length)throw Error('No remaining eligible entries.');let r,limit=Math.floor(4294967296/pool.length)*pool.length;do{r=crypto.getRandomValues(new Uint32Array(1))[0]}while(r>=limit);winner=pool[r%pool.length];winner.won=new Date().toISOString()});if(ok){renderRaffle();$('winner').innerHTML=`<div class="pass"><p>WINNER</p><h2>${esc(winner.name)}</h2><strong>${esc(winner.id)}</strong></div>`}}}
function csvParse(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(value);value=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(v=>v.trim()))rows.push(row);row=[];value=''}else value+=c}if(quoted)throw Error('CSV has an unclosed quote.');row.push(value);if(row.some(v=>v.trim()))rows.push(row);return rows}
function safePerson(p){if(!p||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||typeof p.id!=='string'||!/^PDW27-[A-Za-z0-9-]{1,50}$/.test(p.id))throw Error('Invalid attendee name or ID.');const out={id:p.id,name:p.name.trim(),mobile:typeof p.mobile==='string'?p.mobile.slice(0,30):'',walkin:!!p.walkin};for(const key of ['registration','snack','lunch','raffle','won']){if(p[key]&&(!Number.isFinite(Date.parse(p[key]))||typeof p[key]!=='string'))throw Error('Invalid claim timestamp.');out[key]=p[key]||null}return out}
async function importFile(e){const file=e.target.files[0];if(!file)return;try{const text=await file.text();let incoming;if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(text);if(data.event!==EVENT||!Array.isArray(data.people))throw Error('Choose an event backup JSON.');incoming=data.people.map(safePerson)}else{if(station!=='registration')throw Error('Import CSV on the Registration device, then export a JSON roster to the other stations.');const rows=csvParse(text.replace(/^\uFEFF/,'')),head=rows.shift()?.map(h=>h.toLowerCase().trim())||[];const ni=head.findIndex(x=>['name','full name','participant'].includes(x)),ii=head.findIndex(x=>['id','attendee id'].includes(x)),mi=head.findIndex(x=>['mobile','phone'].includes(x));if(ni<0)throw Error('CSV must have a Name column. Optional columns: ID, Mobile.');const names=new Map(people.map(p=>[p.name.toLowerCase(),p.id]));incoming=rows.map(r=>{const name=(r[ni]||'').trim();let id=ii>=0?r[ii]?.trim():'';if(!id)id=names.get(name.toLowerCase())||'PDW27-'+crypto.randomUUID().slice(0,8).toUpperCase();names.set(name.toLowerCase(),id);return safePerson({name,id,mobile:mi>=0?r[mi]:''})})}if(!incoming.length)throw Error('No attendees found.');if(!confirm(`Import ${incoming.length} records? Existing claims will be preserved. Conflicting IDs will stop the import.`))return;const ok=await change(list=>{for(const p of incoming){const old=list.find(x=>x.id===p.id);if(old){if(old.name.toLowerCase().trim()!==p.name.toLowerCase())throw Error('ID conflict: '+p.id+'. No changes saved.');for(const k of ['registration','snack','lunch','raffle','won'])if(p[k]&&(!old[k]||p[k]<old[k]))old[k]=p[k]}else list.push(p)}});if(ok){renderReport();notice('Import complete. Existing claims preserved.')}}catch(e){notice(e.message)}e.target.value=''}
function exportCSV(){const rows=[['ID','Name','Walk-in','Registration','Snack','Lunch','Raffle','Winner'],...people.map(p=>[p.id,p.name,p.walkin?'Yes':'No',p.registration||'',p.snack||'',p.lunch||'',p.raffle||'',p.won||''])];download(rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n'),'pdw-2027-report.csv','text/csv')}
function renderReport(){$('view').innerHTML=`<div class="reportGrid"><div><h3>Prepare this device</h3><p>1. Open this site while online.<br>2. Choose its station.<br>3. Import the same roster backup.<br>4. Tap Prepare offline, then reopen in airplane mode to test.</p><button id="prepare">Prepare offline</button><p id="offlineStatus" role="status">Checking offline files…</p></div><div><h3>Attendee list & backups</h3><p>${people.length} participants · ${people.filter(p=>p.raffle).length} raffle entries</p><label class="button">Import CSV / backup<input id="import" type="file" accept=".csv,.json" hidden></label><p class="small">Google Sheets: download as CSV with a Name column. Import CSV once on Registration. Export the JSON roster to each claim device.</p><div class="actions"><button id="backup">Export roster / backup</button><button id="csv" class="secondary">Export report CSV</button></div></div></div><div class="hint"><strong>Offline station rule</strong><p>Use one Registration & raffle device, one Snack device, and one Lunch device. These devices do not automatically synchronize, even on the same Wi-Fi. Transfer backup files manually to merge records without clearing claims. Walk-in QR codes carry the name and number; claim staff verify new walk-ins before adding them.</p><p>Keep this browser’s data; clearing it removes this device’s records. Export backups during the event.</p></div>`;$('import').onchange=importFile;$('backup').onclick=()=>download(JSON.stringify({event:EVENT,exportedAt:new Date().toISOString(),station,people},null,2),'pdw27-'+station+'-backup.json','application/json');$('csv').onclick=exportCSV;$('prepare').onclick=prepareOffline;checkOffline()}
async function checkOffline(){if(!('serviceWorker'in navigator)){if($('offlineStatus'))$('offlineStatus').textContent='Offline caching is not supported in this browser.';return}try{const names=await caches.keys();const cache=names.includes('pdw27-offline-v4')?await caches.open('pdw27-offline-v4'):null;const ready=cache&&await cache.match(new URL('index.html',location.href).href);if($('offlineStatus'))$('offlineStatus').textContent=ready?'Offline app files saved. Test reopening with airplane mode.':'Not prepared yet. Stay online and tap Prepare offline.'}catch{if($('offlineStatus'))$('offlineStatus').textContent='Could not verify offline files.'}}
async function prepareOffline(){try{if(!('serviceWorker'in navigator))throw Error('Offline mode needs a supported browser on HTTPS.');$('offlineStatus').textContent='Saving app files…';const reg=await navigator.serviceWorker.register('./sw.js');await reg.update();await navigator.serviceWorker.ready;if(navigator.storage?.persist)await navigator.storage.persist();await checkOffline()}catch(e){$('offlineStatus').textContent='Offline setup failed. Stay online and retry. '+e.message}}
function setup(){stopCamera();$('stationDialog').showModal()}
$('chooseStation').onclick=setup;$('stationForm').onsubmit=e=>{e.preventDefault();const val=new FormData(e.target).get('station');if(!['registration','snack','lunch'].includes(val))return;station=val;localStorage.setItem('pdw27station',val);$('stationDialog').close();stats();home()};$('back').onclick=home;
for(const b of document.querySelectorAll('[data-module]')){if(!JSON.parse(localStorage.getItem('pdw27seen-v2')||'[]').includes(b.dataset.module))b.classList.add('new');b.onclick=()=>show(b.dataset.module)}
window.addEventListener('storage',e=>{if(e.key===KEY){people=read();stats();if($('results'))renderSearch();if(selected&&$('detail'))openPerson(selected)}});
function connectivity(){$('connection').textContent=navigator.onLine?'Connection available':'Offline · records stay on this device'}window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);connectivity();stats();if(!station)setup();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

function downloadRaffleStub(p){
 const c=document.createElement('canvas');c.width=1200;c.height=620;const x=c.getContext('2d');
 x.fillStyle='#fffdf7';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#c9a45d';x.lineWidth=3;x.strokeRect(22,22,1156,576);
 x.textAlign='left';x.fillStyle='#123f32';x.font='bold 22px Arial';x.fillText('PARKINSON’S DISEASE WARRIORS PHILIPPINES',60,80);
 x.fillStyle='#b3202a';x.font='bold 39px Arial';x.fillText('GET TOGETHER',60,140);x.fillStyle='#123f32';x.fillText('2027',410,140);
 x.font='bold 62px Arial';x.fillText('RAFFLE STUB',60,230);
 x.fillStyle='#53675c';x.font='21px Arial';x.fillText('PARTICIPANT',60,295);x.fillStyle='#123f32';let font=36;do{x.font=`bold ${font--}px Arial`}while(x.measureText(p.name).width>685&&font>13);x.fillText(p.name,60,343);
 x.font='21px Arial';x.fillText('RAFFLE NUMBER',60,400);x.font='bold 37px Arial';x.fillText(p.id.replace('PDW27-',''),60,447);
 x.font='21px Arial';x.fillText('Keep this image. Show it to registration staff.',60,518);x.font='18px Arial';x.fillText('One entry after check-in. Official staff records confirm eligibility.',60,556);
 x.setLineDash([8,8]);x.strokeStyle='#c9a45d';x.beginPath();x.moveTo(785,60);x.lineTo(785,560);x.stroke();x.setLineDash([]);
 const qr=qrCanvas(p,310);x.imageSmoothingEnabled=false;x.drawImage(qr,810+(340-qr.width)/2,150);x.textAlign='center';x.fillStyle='#123f32';x.font='bold 19px Arial';x.fillText(p.id,980,500);x.font='18px Arial';x.fillText('SAVE • SHOW • JOIN',980,535);
 c.toBlob(blob=>{if(blob)download(blob,p.id+'-raffle-stub.png','image/png')});
}
