'use strict';
(()=>{
const DOC_TYPES=[
 ['pwd','PWD ID'],['senior','SENIOR CITIZEN ID'],['authorization','AUTHORIZATION LETTER'],['representative','AUTHORIZED REPRESENTATIVE ID']
];
const DOC_DB='pdw27-documents-v1', META_KEY='pdw27-document-meta-v1', AUDIT_KEY='pdw27-document-audit-v1', PENDING_KEY='pdw27-document-pending-v1';
let docSelected=null, currentFile=null, currentType=null, docStream=null;
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta=()=>{try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return {}}};
const saveMeta=m=>localStorage.setItem(META_KEY,JSON.stringify(m));
const audit=()=>{try{return JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]')}catch{return []}};
const log=(id,type,result,staff)=>{const a=audit();a.unshift({at:new Date().toISOString(),id,type,result,staff});localStorage.setItem(AUDIT_KEY,JSON.stringify(a.slice(0,2000)))};
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DOC_DB,1);q.onupgradeneeded=()=>q.result.createObjectStore('files');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putFile(key,file){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(file,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(key){const d=await db();return new Promise((res,rej)=>{const q=d.transaction('files').objectStore('files').get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
const personMeta=id=>{const m=meta();return m[id]||(m[id]={authorized:false,rep:{},docs:{},overall:'INCOMPLETE'})};
function calcOverall(pm){const req=DOC_TYPES.filter(([k])=>(pm.docs[k]?.requirement||'NOT REQUIRED')==='REQUIRED');if(!req.length)return 'VERIFIED';if(req.some(([k])=>pm.docs[k]?.status==='Needs Resubmission'))return 'NEEDS REVIEW';if(req.some(([k])=>!['Verified'].includes(pm.docs[k]?.status)))return req.some(([k])=>pm.docs[k]?.status==='Pending Review')?'PENDING':'INCOMPLETE';return 'VERIFIED'}
function setDoc(id,type,patch){const m=meta(),pm=m[id]||(m[id]={authorized:false,rep:{},docs:{}});pm.docs[type]={requirement:'NOT REQUIRED',status:'Not Submitted',...(pm.docs[type]||{}),...patch};pm.overall=calcOverall(pm);saveMeta(m)}
function statsDoc(){const m=meta(),vals=people.map(p=>(m[p.id]||{}).overall||'INCOMPLETE');return {total:people.length,pending:vals.filter(x=>x==='PENDING').length,verified:vals.filter(x=>x==='VERIFIED').length,review:vals.filter(x=>x==='NEEDS REVIEW').length,incomplete:vals.filter(x=>x==='INCOMPLETE').length}}
function renderDocuments(){
 const s=statsDoc();
 $('view').innerHTML=`<div class="doc-stats"><div><b>${s.total}</b><span>TOTAL ATTENDEES</span></div><div><b>${s.pending}</b><span>PENDING</span></div><div><b>${s.verified}</b><span>VERIFIED</span></div><div><b>${s.review}</b><span>NEEDS REVIEW</span></div><div><b>${s.incomplete}</b><span>INCOMPLETE</span></div></div>
 <label for="docQuery">SEARCH ATTENDEE</label><input id="docQuery" placeholder="Name, nickname, mobile, attendee/pass number" autocomplete="off">
 <div class="doc-filters">${['ALL','PENDING','VERIFIED','INCOMPLETE','NEEDS REVIEW'].map(x=>`<button data-doc-filter="${x}" class="secondary">${x}</button>`).join('')}</div>
 <div id="docResults"></div><div id="docDetail"></div>`;
 let filter='ALL';const draw=()=>{const q=$('docQuery').value.trim().toLowerCase(),m=meta();let list=people.filter(p=>(p.name+' '+(p.nickname||'')+' '+(p.mobile||'')+' '+p.id).toLowerCase().includes(q));if(filter!=='ALL')list=list.filter(p=>((m[p.id]||{}).overall||'INCOMPLETE')===filter);$('docResults').innerHTML=list.slice(0,100).map(p=>{const pm=m[p.id]||{},d=pm.docs||{};return `<div class="person doc-person"><span><strong>${E(p.name)}</strong><br><small>${E(p.id)} · PWD ${statusShort(d.pwd)} · SENIOR ${statusShort(d.senior)} · AUTH ${statusShort(d.authorization)}<br><b>${E(pm.overall||'INCOMPLETE')}</b></small></span><button data-doc-open="${E(p.id)}">Open</button></div>`}).join('')||'<div class="empty-state"><strong>No matching attendees</strong><p>Try another search or filter.</p></div>';document.querySelectorAll('[data-doc-open]').forEach(b=>b.onclick=()=>openDocs(b.dataset.docOpen))};
 $('docQuery').oninput=draw;document.querySelectorAll('[data-doc-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.docFilter;draw()});draw();
}
function statusShort(d){if(!d)return '○';if(d.requirement==='NOT APPLICABLE')return '—';return d.status==='Verified'?'✓':d.status==='Needs Resubmission'?'⚠':d.status==='Pending Review'?'◌':'○'}
function ensureDefaults(id){const m=meta(),pm=m[id]||(m[id]={authorized:false,rep:{},docs:{}});DOC_TYPES.forEach(([k])=>pm.docs[k]||(pm.docs[k]={requirement:'NOT REQUIRED',status:'Not Submitted'}));pm.overall=calcOverall(pm);saveMeta(m);return pm}
function openDocs(id){docSelected=id;const p=people.find(x=>x.id===id);if(!p)return;const pm=ensureDefaults(id);$('docDetail').innerHTML=`<div class="doc-workspace"><h3>${E(p.name)}</h3><p><strong>${E(p.id)}</strong></p><div class="doc-overall">DOCUMENTS · ${E(pm.overall)}</div>
 ${DOC_TYPES.map(([k,label])=>docCard(id,k,label,pm.docs[k])).join('')}
 <div class="doc-rep"><label><input type="checkbox" id="authorizedRep" ${pm.authorized?'checked':''}> AUTHORIZED REPRESENTATIVE</label><div id="repFields" ${pm.authorized?'':'hidden'}><label>Representative Full Name<input id="repName" value="${E(pm.rep?.name||'')}"></label><label>Relationship to Participant<input id="repRelationship" value="${E(pm.rep?.relationship||'')}"></label><label>Mobile Number<input id="repMobile" type="tel" value="${E(pm.rep?.mobile||'')}"></label><button id="saveRep">SAVE REPRESENTATIVE DETAILS</button><button id="verifyRep" class="secondary">VERIFY REPRESENTATIVE</button></div></div>
 <div class="doc-audit"><h3>Audit trail</h3>${audit().filter(a=>a.id===id).slice(0,20).map(a=>`<p><b>${new Date(a.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b> · ${E(a.type)} ${E(a.result)}<br><small>Staff: ${E(a.staff||'Verification staff')}</small></p>`).join('')||'<p>No verification actions yet.</p>'}</div></div>`;
 bindDocActions(id);$('docDetail').scrollIntoView({behavior:'smooth',block:'start'});
}
function docCard(id,k,label,d){return `<section class="doc-card"><h3>${label}</h3><label>Requirement<select data-req="${k}"><option ${d.requirement==='REQUIRED'?'selected':''}>REQUIRED</option><option ${d.requirement==='NOT REQUIRED'?'selected':''}>NOT REQUIRED</option><option ${d.requirement==='NOT APPLICABLE'?'selected':''}>NOT APPLICABLE</option></select></label><p>Status: <strong>${E(d.status||'Not Submitted')}</strong>${d.pendingSync?' · PENDING SYNC':''}</p><div class="doc-actions"><button data-capture="${k}">TAKE PHOTO</button><label class="button secondary">UPLOAD FILE<input data-upload="${k}" type="file" accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" hidden></label><button data-view="${k}" class="secondary">VIEW</button><button data-verify="${k}">VERIFY</button><button data-reject="${k}" class="secondary">REJECT / RESUBMIT</button></div></section>`}
function staffName(){let n=sessionStorage.getItem('pdw27-verification-staff');if(!n){n=prompt('Verification staff name:')?.trim()||'Verification staff';sessionStorage.setItem('pdw27-verification-staff',n)}return n}
function privacyOK(){if(sessionStorage.getItem('pdw27-doc-privacy')==='1')return true;const ok=confirm('DOCUMENT PRIVACY NOTICE\n\nThe documents submitted through this system are collected only for authorized event registration, eligibility, identity, and document-verification purposes.\n\nAccess is limited to authorized personnel.\n\nDocuments must not be used for unrelated purposes and should be retained only for the approved retention period.\n\nSelect OK for I UNDERSTAND — CONTINUE.');if(ok)sessionStorage.setItem('pdw27-doc-privacy','1');return ok}
function bindDocActions(id){
 document.querySelectorAll('[data-req]').forEach(s=>s.onchange=()=>{setDoc(id,s.dataset.req,{requirement:s.value,status:s.value==='NOT APPLICABLE'?'Not Applicable':(personMeta(id).docs[s.dataset.req]?.status||'Not Submitted')});openDocs(id)});
 document.querySelectorAll('[data-upload]').forEach(i=>i.onchange=e=>{const f=e.target.files[0];if(f)previewFile(id,i.dataset.upload,f)});
 document.querySelectorAll('[data-capture]').forEach(b=>b.onclick=()=>captureDoc(id,b.dataset.capture));
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewDoc(id,b.dataset.view));
 document.querySelectorAll('[data-verify]').forEach(b=>b.onclick=()=>{const staff=staffName();setDoc(id,b.dataset.verify,{status:'Verified',verifiedBy:staff,verifiedAt:new Date().toISOString()});log(id,b.dataset.verify,'verified',staff);openDocs(id);renderDocumentsAfterDetail(id)});
 document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{const staff=staffName();setDoc(id,b.dataset.reject,{status:'Needs Resubmission',verifiedBy:staff,verifiedAt:new Date().toISOString()});log(id,b.dataset.reject,'needs resubmission',staff);openDocs(id);renderDocumentsAfterDetail(id)});
 const t=$('authorizedRep');if(t)t.onchange=()=>{const m=meta();m[id]=m[id]||{docs:{},rep:{}};m[id].authorized=t.checked;if(t.checked){m[id].docs.authorization={...(m[id].docs.authorization||{}),requirement:'REQUIRED'};m[id].docs.representative={...(m[id].docs.representative||{}),requirement:'REQUIRED'}}m[id].overall=calcOverall(m[id]);saveMeta(m);openDocs(id)};
 if($('saveRep'))$('saveRep').onclick=()=>{const m=meta();m[id].rep={name:$('repName').value.trim(),relationship:$('repRelationship').value.trim(),mobile:$('repMobile').value.trim()};saveMeta(m);notice('Representative details saved.')};
 if($('verifyRep'))$('verifyRep').onclick=()=>{const staff=staffName(),m=meta();m[id].rep={name:$('repName').value.trim(),relationship:$('repRelationship').value.trim(),mobile:$('repMobile').value.trim(),verified:true,verifiedBy:staff,verifiedAt:new Date().toISOString()};saveMeta(m);log(id,'authorized representative','verified',staff);openDocs(id)};
}
function renderDocumentsAfterDetail(id){renderDocuments();openDocs(id)}
async function previewFile(id,type,file){if(!privacyOK())return;if(!/^(image\/jpeg|image\/png|application\/pdf)$/.test(file.type)){notice('Use JPG, JPEG, PNG, or PDF.');return}currentFile=file;currentType=type;const url=URL.createObjectURL(file),isPdf=file.type==='application/pdf';const box=document.createElement('dialog');box.className='doc-preview';box.innerHTML=`<div><h2>Document preview</h2>${isPdf?'<p>PDF ready to save: '+E(file.name)+'</p>':`<img src="${url}" alt="Document preview">`}<div class="doc-actions"><button id="docSave">SAVE DOCUMENT</button><button id="docReplace" class="secondary">REPLACE</button><button id="docCancel" class="secondary">CANCEL</button></div></div>`;document.body.append(box);box.showModal();$('docSave').onclick=async()=>{const key=id+'::'+type;await putFile(key,file);const pending=!navigator.onLine;setDoc(id,type,{status:'Pending Review',fileName:file.name,mime:file.type,pendingSync:pending,savedAt:new Date().toISOString()});log(id,type,pending?'saved locally · pending sync':'uploaded to protected local storage',staffName());box.close();box.remove();URL.revokeObjectURL(url);renderDocumentsAfterDetail(id);notice(pending?'OFFLINE — DOCUMENT SAVED LOCALLY · WILL SYNC WHEN CONNECTION RETURNS':'Document saved securely on this device for verification.')};$('docReplace').onclick=()=>{box.close();box.remove();URL.revokeObjectURL(url);document.querySelector('[data-upload="'+type+'"]')?.click()};$('docCancel').onclick=()=>{box.close();box.remove();URL.revokeObjectURL(url)}}
async function captureDoc(id,type){if(!privacyOK())return;try{docStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const dlg=document.createElement('dialog');dlg.className='doc-preview';dlg.innerHTML='<div><h2>Take photo</h2><video id="docCam" autoplay playsinline></video><canvas id="docCanvas" hidden></canvas><div class="doc-actions"><button id="snapDoc">CAPTURE</button><button id="cancelCam" class="secondary">CANCEL</button></div></div>';document.body.append(dlg);dlg.showModal();$('docCam').srcObject=docStream;$('snapDoc').onclick=()=>{const v=$('docCam'),c=$('docCanvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(blob=>{docStream.getTracks().forEach(t=>t.stop());dlg.close();dlg.remove();previewFile(id,type,new File([blob],type+'-'+Date.now()+'.jpg',{type:'image/jpeg'}))},'image/jpeg',.9)};$('cancelCam').onclick=()=>{docStream.getTracks().forEach(t=>t.stop());dlg.close();dlg.remove()}}catch(e){const useUpload=confirm('NO CAMERA DETECTED\n\nOK — UPLOAD FILE\nCancel — close and connect a scanner/webcam, then try TAKE PHOTO again.');if(useUpload)document.querySelector('[data-upload="'+type+'"]')?.click()}}
async function viewDoc(id,type){const f=await getFile(id+'::'+type);if(!f)return notice('No saved document file on this device.');const url=URL.createObjectURL(f);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function syncPending(){if(!navigator.onLine)return;const m=meta();let changed=false;Object.values(m).forEach(pm=>Object.values(pm.docs||{}).forEach(d=>{if(d.pendingSync){d.pendingSync=false;d.syncedAt=new Date().toISOString();changed=true}}));if(changed){saveMeta(m);if(active==='documents')renderDocuments();notice('Connection restored. Pending document metadata marked synced. File copies remain protected on this device until a cloud-storage connector is configured.')}}
window.addEventListener('online',syncPending);
const originalShow=show;
show=function(id){if(id!=='documents')return originalShow(id);stopCamera();mark(id);active=id;document.body.dataset.screen='module';requestAnimationFrame(applyPhoneModuleScale);selected=null;$('notice').hidden=true;$('orbitHome').hidden=true;$('orbitHome').style.display='none';$('content').hidden=false;$('content').style.display='block';$('viewTitle').textContent='Document Verification';renderDocuments();decorateModule('documents');window.scrollTo(0,0)};
const originalDecorate=decorateModule;
decorateModule=function(id){if(id!=='documents')return originalDecorate(id);$('content').dataset.module=id;document.querySelectorAll('.module-eyebrow,.module-description,.module-steps,.module-summary').forEach(n=>n.remove());const e=document.createElement('p');e.className='module-eyebrow';e.textContent='GET TOGETHER 2027 / SECURE STAFF WORKSPACE';$('viewTitle').before(e);const p=document.createElement('p');p.className='module-description';p.textContent='Verify only the documents required for each attendee. ID images never appear on public passes or claim screens.';$('viewTitle').after(p)};
document.addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('[data-module="documents"]');if(b&&!JSON.parse(localStorage.getItem('pdw27seen-v2')||'[]').includes('documents'))b.classList.add('new')});
})();